language: c

compiler:
    - gcc
    
git:
  depth: 1

install:
    - sudo pip install cpp-coveralls --use-mirrors
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake python3-minimal
    - sudo apt-get install -qq valgrind
    - sudo apt-get install -qq libfuzzy-dev
    - sudo apt-get install -qq libglib2.0-dev
    - sudo apt-get install -qq libconfig-dev

script:
    - ./clean.py --rebuild
    - cd build
    - cmake ..
    - make
    #- make coverage DEBUG=yes

after_success:
    #- coveralls


